apiVersion: klot.io/v1
kind: KlotIOApp
metadata:
  name: chore-speech.nandy.io
spec:
  namespace: chore-speech-nandy-io
  description: Chore Speech - Nandy I/O
  manifests:
  - path: daemon/kubernetes/daemon.yaml
  requires:
  - name: people.nandy.io
    source:
      site: github.com
      repo: nandy-io/people
    integrations:
    - path: daemon/forms/person.fields.yaml
  - name: chore.nandy.io
    source:
      site: github.com
      repo: nandy-io/chore
    integrations:
    - path: daemon/forms/area.fields.yaml
    - path: daemon/forms/act.fields.yaml
    - path: daemon/forms/todo.fields.yaml
    - path: daemon/forms/routine.fields.yaml
  - name: speech.nandy.io
    source:
      site: github.com
      repo: nandy-io/speech
