apiVersion: klot.io/v1
kind: KlotIOApp
metadata:
  name: chore-speech.nandy.io
spec:
  namespace: chore-speech-nandy-io
  description: Chore Speech - Nandy I/O
  manifests:
  - path: kubernetes/namespace.yaml
  - path: daemon/kubernetes/daemon.yaml
  requires:
  - name: chore.nandy.io
    source:
      site: github.com
      repo: nandy-io/chore
  - name: speech.nandy.io
    source:
      site: github.com
      repo: nandy-io/speech
