apiVersion: klot.io/v1
kind: App
metadata:
  name: chore-speech.nandy.io
  description: Chore Speech - Nandy I/O
spec:
  source:
    site: github.com
    repo: nandy-io/chore-speech
  namespace: chore-speech-nandy-io
  manifests:
  - path: kubernetes/namespace.yaml
  - path: daemon/kubernetes/daemon.yaml
  requires:
  - site: github.com
    repo: nandy-io/chore
  - site: github.com
    repo: nandy-io/speech
